services:

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: institute

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  irp-app:
    image: shevendrasinghchandel/irp-app:v1
    container_name: irp-app
    restart: always

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/institute
      DB_USER: root
      DB_PASS: root

      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}

      TWILIO_SID: ${TWILIO_SID}
      TWILIO_TOKEN: ${TWILIO_TOKEN}
      TWILIO_PHONE: ${TWILIO_PHONE}

    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data: